version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  build:
    executor:
      name: node/default
      tag: '16.20.2'
    steps:
      - checkout
      - run:
          name: install & lint build & export
          command: npm run export